import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import Topnav from "@/components/topnav/topnav";
import Footer from "@/components/footer/footer";


const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <div className="">
          <Topnav/>
          <div className="lg:m-auto lg:max-w-[70rem]">
            {children}
          </div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
